services:
  app:
    image: python-app
    build:
      context: ./app/
    env_file:
      - ./app.env
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-net
  db:
    image: mysql:8.0
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - ./app.env
    expose:
      - 3306
      - 33060
    healthcheck:
      test: [ "CMD-SHELL", 'mysqladmin ping -h 127.0.0.1 --user="${MYSQL_USER}" --password="${MYSQL_PASSWORD}" --silent' ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 1m
    networks:
      - app-net
volumes:
  db-data:
networks:
  app-net:
